name: Trigger Jenkins Job with Branch Parameter

on:
  push:
    branches:
      - main
      - develop

jobs:
  trigger-jenkins:
    environment: JENKINS
    runs-on: ubuntu-latest

    steps:
      - name: Debug Environment Variables
        run: |
          echo "JENKINS_URL=${{ secrets.JENKINS_URL }}"
          echo "JENKINS_JOB_NAME=${{ secrets.JENKINS_JOB_NAME }}"
          echo "Branch: ${{ github.ref_name }}"
      - name: Call Jenkins Job with Branch Parameter
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/job/${{ secrets.JENKINS_JOB_NAME }}/buildWithParameters" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
          --data token=${{ secrets.JENKINS_JOB_TOKEN }} \
          --data branch=${{ github.ref_name }}
